#!/usr/bin/env bash
################################################################################
# RKE2 Master Node Installation Script
# Usage:
#   ./install-master.sh <node_ip> <is_init_node> <config_file>
#
# Arguments:
#   node_ip      - IP address of the master node
#   is_init_node - "true" for bootstrap master, "false" for additional masters
#   config_file  - Path to generated RKE2 config YAML
#
# Prerequisites:
#   - SSH access to the node
#   - Config files generated by Terraform in rke2/configs/
#   - inventory.ini present in rke2/configs/
################################################################################

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIGS_DIR="${SCRIPT_DIR}/../configs"
SECRETS_DIR="${SCRIPT_DIR}/../../.secrets"

# ─── Load inventory ───────────────────────────────────────────────────────────
INVENTORY="${CONFIGS_DIR}/inventory.ini"
[[ -f "$INVENTORY" ]] || { echo "ERROR: inventory.ini not found. Run terraform apply first."; exit 1; }

SSH_USER=$(grep 'ansible_user=' "$INVENTORY" | head -1 | cut -d= -f2)
SSH_KEY=$(grep 'ansible_ssh_private_key_file=' "$INVENTORY" | head -1 | cut -d= -f2 | tr -d '"')
CONTROL_PLANE_VIP=$(grep 'control_plane_vip=' "$INVENTORY" | head -1 | cut -d= -f2)
RKE2_VERSION=$(grep 'rke2_version=' "$INVENTORY" | head -1 | cut -d= -f2)
CLUSTER_NAME=$(grep 'cluster_name=' "$INVENTORY" | head -1 | cut -d= -f2)

SSH_OPTS="-o StrictHostKeyChecking=no -o ConnectTimeout=30 -i ${SSH_KEY}"

ssh_exec() {
  local host="$1"; shift
  ssh ${SSH_OPTS} "${SSH_USER}@${host}" "$@"
}

scp_file() {
  local src="$1" dst_host="$2" dst_path="$3"
  scp ${SSH_OPTS} "$src" "${SSH_USER}@${dst_host}:${dst_path}"
}

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }
err() { echo "[ERROR] $*" >&2; exit 1; }

# ─── Install a single master node ─────────────────────────────────────────────

install_master() {
  local node_ip="$1"
  local is_init="$2"
  local config_file="$3"
  local node_index="${4:-0}"

  log "Installing RKE2 master on ${node_ip} (init=${is_init})"

  # 1. Upload RKE2 configuration
  ssh_exec "$node_ip" "sudo mkdir -p /etc/rancher/rke2"
  scp_file "$config_file" "$node_ip" "/tmp/rke2-config.yaml"
  ssh_exec "$node_ip" "sudo mv /tmp/rke2-config.yaml /etc/rancher/rke2/config.yaml && sudo chmod 600 /etc/rancher/rke2/config.yaml"

  # 2. Upload audit policy
  scp_file "${CONFIGS_DIR}/audit-policy.yaml" "$node_ip" "/tmp/audit-policy.yaml" 2>/dev/null || \
    ssh_exec "$node_ip" "sudo tee /tmp/audit-policy.yaml > /dev/null" < "${SCRIPT_DIR}/../configs/audit-policy.yaml"
  ssh_exec "$node_ip" "sudo mkdir -p /etc/rancher/rke2 && sudo mv /tmp/audit-policy.yaml /etc/rancher/rke2/audit-policy.yaml"

  # 3. Download and install RKE2
  log "Downloading RKE2 ${RKE2_VERSION}..."
  ssh_exec "$node_ip" "
    curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_VERSION='${RKE2_VERSION}' INSTALL_RKE2_TYPE='server' sh -
  "

  # 4. Inject cluster token
  if [[ "$is_init" == "true" ]]; then
    # Generate a secure token and save it
    CLUSTER_TOKEN=$(openssl rand -hex 32)
    echo "$CLUSTER_TOKEN" > "${SECRETS_DIR}/rke2-cluster-token"
    chmod 600 "${SECRETS_DIR}/rke2-cluster-token"
    log "Generated cluster token → ${SECRETS_DIR}/rke2-cluster-token"
  else
    [[ -f "${SECRETS_DIR}/rke2-cluster-token" ]] || err "Cluster token not found. Install init master first."
    CLUSTER_TOKEN=$(cat "${SECRETS_DIR}/rke2-cluster-token")
  fi

  # Inject token into config.yaml (RKE2 reads token: from config, not a token file)
  ssh_exec "$node_ip" "sudo sed -i '/^token:/d' /etc/rancher/rke2/config.yaml; echo 'token: ${CLUSTER_TOKEN}' | sudo tee -a /etc/rancher/rke2/config.yaml > /dev/null"

  # 5. On init master: deploy kube-vip + Cilium IngressController config
  if [[ "$is_init" == "true" ]]; then
    log "Setting up kube-vip for HA VIP ${CONTROL_PLANE_VIP}..."
    VIP_INTERFACE=$(grep 'control_plane_vip_interface' "${CONFIGS_DIR}/master-1-config.yaml" 2>/dev/null | awk '{print $2}' || echo "eth0")
    ssh_exec "$node_ip" "
      sudo mkdir -p /var/lib/rancher/rke2/server/manifests
      sudo tee /var/lib/rancher/rke2/server/manifests/kube-vip.yaml > /dev/null << 'KVEOF'
$(generate_kubevip_manifest "$CONTROL_PLANE_VIP" "$VIP_INTERFACE")
KVEOF
    "

    # Deploy Cilium HelmChartConfig before RKE2 starts so Cilium is configured
    # with IngressController + Hubble + WireGuard encryption on first boot
    log "Deploying Cilium IngressController configuration..."
    local cilium_config="${CONFIGS_DIR}/rke2-cilium-config.yaml"
    # Patch in the actual control plane VIP
    sed "s/CONTROL_PLANE_VIP_PLACEHOLDER/${CONTROL_PLANE_VIP}/g" "$cilium_config" > /tmp/cilium-config-patched.yaml
    scp_file /tmp/cilium-config-patched.yaml "$node_ip" "/tmp/rke2-cilium-config.yaml"
    ssh_exec "$node_ip" "
      sudo mv /tmp/rke2-cilium-config.yaml /var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml
      sudo chmod 600 /var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml
    "
    rm -f /tmp/cilium-config-patched.yaml
    log "  Cilium config deployed — IngressController + Hubble + WireGuard will activate on RKE2 start"
  fi

  # 6. Apply kernel settings required by kubelet protect-kernel-defaults
  log "Applying kernel sysctl settings..."
  ssh_exec "$node_ip" "
    sudo sysctl -w kernel.panic=10
    sudo sysctl -w kernel.panic_on_oops=1
    echo 'kernel.panic=10' | sudo tee -a /etc/sysctl.d/99-rke2.conf
    echo 'kernel.panic_on_oops=1' | sudo tee -a /etc/sysctl.d/99-rke2.conf
    sudo sysctl --system
  "

  # 7. Enable and start RKE2
  log "Starting RKE2 server service..."
  ssh_exec "$node_ip" "
    sudo systemctl daemon-reload
    sudo systemctl enable rke2-server
    sudo systemctl start rke2-server
  "

  # 7. Wait for RKE2 to be ready
  log "Waiting for RKE2 to become ready on ${node_ip}..."
  local max_wait=300
  local waited=0
  while ! ssh_exec "$node_ip" "sudo /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get nodes 2>/dev/null | grep -q Ready"; do
    sleep 10
    waited=$((waited + 10))
    [[ $waited -lt $max_wait ]] || err "Timeout waiting for RKE2 on ${node_ip}"
    log "  Still waiting... (${waited}/${max_wait}s)"
  done

  log "✓ RKE2 master ready on ${node_ip}"

  # 8. Retrieve kubeconfig from init master
  if [[ "$is_init" == "true" ]]; then
    log "Retrieving kubeconfig..."
    mkdir -p "${SECRETS_DIR}"
    ssh_exec "$node_ip" "sudo cat /etc/rancher/rke2/rke2.yaml" | \
      sed "s/127.0.0.1/${CONTROL_PLANE_VIP}/g" > "${SECRETS_DIR}/kubeconfig-admin.yaml"
    chmod 600 "${SECRETS_DIR}/kubeconfig-admin.yaml"
    log "Admin kubeconfig → ${SECRETS_DIR}/kubeconfig-admin.yaml"
  fi
}

generate_kubevip_manifest() {
  local vip="$1"
  local iface="$2"
  cat << EOF
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:kube-vip-role
rules:
  - apiGroups: [""]
    resources: ["services","services/status","nodes","endpoints"]
    verbs: ["list","get","watch","update"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["list","get","watch","create","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:kube-vip-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-vip-role
subjects:
  - kind: ServiceAccount
    name: kube-vip
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: kube-vip-ds
  template:
    metadata:
      labels:
        app: kube-vip-ds
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
      containers:
        - name: kube-vip
          image: ghcr.io/kube-vip/kube-vip:v0.7.2
          args:
            - manager
          env:
            - name: vip_arp
              value: "true"
            - name: vip_interface
              value: "${iface}"
            - name: address
              value: "${vip}"
            - name: port
              value: "6443"
            - name: vip_cidr
              value: "32"
            - name: cp_enable
              value: "true"
            - name: cp_namespace
              value: kube-system
            - name: vip_ddns
              value: "false"
            - name: svc_enable
              value: "true"
            - name: lb_enable
              value: "true"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          volumeMounts:
            - mountPath: /etc/kubernetes/admin.conf
              name: kubeconfig
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      volumes:
        - name: kubeconfig
          hostPath:
            path: /etc/rancher/rke2/rke2.yaml
EOF
}

# ─── Main Execution ───────────────────────────────────────────────────────────

main() {
  log "=== RKE2 Master Installation ==="
  log "Cluster: ${CLUSTER_NAME}"
  log "VIP: ${CONTROL_PLANE_VIP}"
  log "RKE2 Version: ${RKE2_VERSION}"

  mkdir -p "${SECRETS_DIR}"

  # Parse master IPs from inventory
  mapfile -t MASTER_LINES < <(grep -A100 '^\[masters\]' "$INVENTORY" | tail -n +2 | grep -v '^\[' | grep -v '^$')

  local idx=0
  for line in "${MASTER_LINES[@]}"; do
    [[ -z "$line" || "$line" =~ ^\[ ]] && break
    local node_host
    node_host=$(echo "$line" | awk '{print $1}')
    local node_ip
    node_ip=$(echo "$line" | grep -oP 'ansible_host=\K[^ ]+')
    local is_init
    is_init=$(echo "$line" | grep -oP 'is_init_node=\K[^ ]+' || echo "false")

    local config_file="${CONFIGS_DIR}/master-$((idx + 1))-config.yaml"
    [[ -f "$config_file" ]] || err "Config not found: ${config_file}"

    if [[ "$is_init" == "True" || "$is_init" == "true" ]]; then
      install_master "$node_ip" "true" "$config_file" "$idx"
    else
      # Non-init masters wait for init master to be ready
      log "Waiting 30s before joining additional master ${node_ip}..."
      sleep 30
      install_master "$node_ip" "false" "$config_file" "$idx"
    fi

    idx=$((idx + 1))
  done

  log ""
  log "=== All master nodes installed successfully ==="
  log "Next step: run install-worker.sh"
  log "Admin kubeconfig: ${SECRETS_DIR}/kubeconfig-admin.yaml"
  log ""
  log "Test: kubectl --kubeconfig ${SECRETS_DIR}/kubeconfig-admin.yaml get nodes"

  # Install Grafana Alloy on all master nodes (OS-level, systemd service)
  # Alloy collects: pod logs, journald, node metrics, etcd metrics
  log ""
  log "=== Installing Grafana Alloy on master nodes ==="
  # shellcheck source=install-alloy.sh
  source "${SCRIPT_DIR}/install-alloy.sh"

  local in_section=false
  while IFS= read -r line; do
    [[ "$line" =~ ^\[masters\] ]] && { in_section=true; continue; }
    [[ "$line" =~ ^\[ ]]         && { in_section=false; continue; }
    [[ "$in_section" == false || -z "$line" ]] && continue
    local node_ip; node_ip=$(echo "$line" | grep -oP 'ansible_host=\K[^ ]+')
    install_alloy "$node_ip" "master" "$SSH_USER" "$SSH_KEY"
  done < "$INVENTORY"
}

main "$@"
