#!/usr/bin/env bash
################################################################################
# RKE2 Master Node Installation Script — Idempotent
# Re-running skips completed steps and continues from where it left off.
#
# Usage: ./install-master.sh
# Prerequisites:
#   - rke2/configs/inventory.ini (generated by terraform apply)
#   - rke2/configs/master-N-config.yaml (generated by terraform apply)
################################################################################

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIGS_DIR="${SCRIPT_DIR}/../configs"
SECRETS_DIR="${SCRIPT_DIR}/../../.secrets"

# ─── Load inventory ───────────────────────────────────────────────────────────
INVENTORY="${CONFIGS_DIR}/inventory.ini"
[[ -f "$INVENTORY" ]] || { echo "ERROR: inventory.ini not found. Run terraform apply first."; exit 1; }

SSH_USER=$(grep 'ansible_user='                    "$INVENTORY" | head -1 | cut -d= -f2)
SSH_KEY=$(grep  'ansible_ssh_private_key_file='    "$INVENTORY" | head -1 | cut -d= -f2 | tr -d '"')
CONTROL_PLANE_VIP=$(grep 'control_plane_vip='      "$INVENTORY" | head -1 | cut -d= -f2)
RKE2_VERSION=$(grep      'rke2_version='            "$INVENTORY" | head -1 | cut -d= -f2)
CLUSTER_NAME=$(grep      'cluster_name='            "$INVENTORY" | head -1 | cut -d= -f2)

SSH_OPTS="-o StrictHostKeyChecking=no -o ConnectTimeout=30 -i ${SSH_KEY}"

ssh_exec() { local host="$1"; shift; ssh ${SSH_OPTS} "${SSH_USER}@${host}" "$@"; }
scp_file()  { scp ${SSH_OPTS} "$1" "${SSH_USER}@${2}:${3}"; }
log()       { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }
err()       { echo "[ERROR] $*" >&2; exit 1; }

# ─── Idempotency checks ───────────────────────────────────────────────────────

node_is_ready() {
  local node_ip="$1"
  ssh_exec "$node_ip" "
    sudo /var/lib/rancher/rke2/bin/kubectl \
      --kubeconfig /etc/rancher/rke2/rke2.yaml \
      get nodes \$(hostname -s) 2>/dev/null | grep -qw Ready
  " 2>/dev/null
}

rke2_installed() {
  ssh_exec "$1" "test -f /usr/local/bin/rke2" 2>/dev/null
}

service_active() {
  ssh_exec "$1" "sudo systemctl is-active rke2-server >/dev/null 2>&1" 2>/dev/null
}

kubeconfig_saved() {
  [[ -f "${SECRETS_DIR}/kubeconfig-admin.yaml" ]]
}

# ─── Install a single master node (idempotent) ────────────────────────────────

install_master() {
  local node_ip="$1"
  local is_init="$2"
  local config_file="$3"

  log "──────────────────────────────────────────"
  log "Master: ${node_ip}  (init=${is_init})"
  log "──────────────────────────────────────────"

  # ── SKIP: already Ready ───────────────────────────────────────────────────
  if node_is_ready "$node_ip"; then
    log "✓ Node ${node_ip} already Ready — skipping"
    if [[ "$is_init" == "true" ]] && ! kubeconfig_saved; then
      retrieve_kubeconfig "$node_ip"
    fi
    return 0
  fi

  # ── STEP 1: Upload config ─────────────────────────────────────────────────
  log "[1/7] Uploading RKE2 config..."
  ssh_exec "$node_ip" "sudo mkdir -p /etc/rancher/rke2"
  scp_file "$config_file" "$node_ip" "/tmp/rke2-config.yaml"
  ssh_exec "$node_ip" "sudo mv /tmp/rke2-config.yaml /etc/rancher/rke2/config.yaml && sudo chmod 600 /etc/rancher/rke2/config.yaml"

  # Upload audit policy
  scp_file "${CONFIGS_DIR}/audit-policy.yaml" "$node_ip" "/tmp/audit-policy.yaml"
  ssh_exec "$node_ip" "sudo mv /tmp/audit-policy.yaml /etc/rancher/rke2/audit-policy.yaml"

  # ── STEP 2: Install RKE2 binary ───────────────────────────────────────────
  if rke2_installed "$node_ip"; then
    log "[2/7] RKE2 already installed — skipping download"
  else
    log "[2/7] Installing RKE2 ${RKE2_VERSION}..."
    ssh_exec "$node_ip" "
      curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_VERSION='${RKE2_VERSION}' INSTALL_RKE2_TYPE='server' sh -
    "
  fi

  # ── STEP 3: Inject cluster token into config.yaml ─────────────────────────
  log "[3/7] Setting cluster token..."
  if [[ "$is_init" == "true" ]]; then
    if [[ -f "${SECRETS_DIR}/rke2-cluster-token" ]]; then
      log "  Token already exists — reusing ${SECRETS_DIR}/rke2-cluster-token"
    else
      openssl rand -hex 32 > "${SECRETS_DIR}/rke2-cluster-token"
      chmod 600 "${SECRETS_DIR}/rke2-cluster-token"
      log "  Generated new token → ${SECRETS_DIR}/rke2-cluster-token"
    fi
    CLUSTER_TOKEN=$(cat "${SECRETS_DIR}/rke2-cluster-token")
  else
    [[ -f "${SECRETS_DIR}/rke2-cluster-token" ]] || err "Token not found. Install init master first."
    CLUSTER_TOKEN=$(cat "${SECRETS_DIR}/rke2-cluster-token")
  fi
  # Always inject — sed removes old entry first so it's idempotent
  ssh_exec "$node_ip" "
    sudo sed -i '/^token:/d' /etc/rancher/rke2/config.yaml
    echo 'token: ${CLUSTER_TOKEN}' | sudo tee -a /etc/rancher/rke2/config.yaml > /dev/null
  "

  # ── STEP 4: Deploy manifests on init master ───────────────────────────────
  if [[ "$is_init" == "true" ]]; then
    log "[4/7] Deploying kube-vip + Cilium manifests..."
    local vip_iface
    vip_iface=$(grep 'control_plane_vip_interface' "${CONFIGS_DIR}/master-1-config.yaml" 2>/dev/null | awk '{print $2}' || echo "eth0")

    ssh_exec "$node_ip" "sudo mkdir -p /var/lib/rancher/rke2/server/manifests"

    # kube-vip
    ssh_exec "$node_ip" "
      sudo tee /var/lib/rancher/rke2/server/manifests/kube-vip.yaml > /dev/null << 'KVEOF'
$(generate_kubevip_manifest "${CONTROL_PLANE_VIP}" "${vip_iface}")
KVEOF
    "

    # Cilium HelmChartConfig — point k8sServiceHost at this init master's
    # direct IP, not the VIP. kube-vip can't bind the VIP until it has API
    # access (chicken-and-egg with Cilium kube-proxy replacement), so Cilium
    # must reach the apiserver via a directly-routable address.
    local cilium_config="${CONFIGS_DIR}/rke2-cilium-config.yaml"
    sed "s/CONTROL_PLANE_VIP_PLACEHOLDER/${node_ip}/g" "$cilium_config" > /tmp/cilium-patched.yaml
    scp_file /tmp/cilium-patched.yaml "$node_ip" "/tmp/rke2-cilium-config.yaml"
    ssh_exec "$node_ip" "
      sudo mv /tmp/rke2-cilium-config.yaml /var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml
      sudo chmod 600 /var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml
    "
    rm -f /tmp/cilium-patched.yaml

    # CoreDNS HelmChartConfig — inject a `hosts` plugin so the bare
    # hostname `kubernetes` resolves to a master IP. kube-vip v0.7.2
    # hardcodes its apiserver URL as `https://kubernetes:6443`, and
    # CoreDNS won't resolve the bare name out of the box.
    local coredns_config="${CONFIGS_DIR}/rke2-coredns-config.yaml"
    local hosts_block
    hosts_block=$(printf '              %s kubernetes\n' \
      $(awk '/^\[masters\]/{f=1; next} /^\[/{f=0} f' "$INVENTORY" \
        | grep -oP 'ansible_host=\K[^ ]+'))
    awk -v block="$hosts_block" '/MASTER_IPS_PLACEHOLDER/{print block; next} {print}' \
      "$coredns_config" > /tmp/coredns-patched.yaml
    scp_file /tmp/coredns-patched.yaml "$node_ip" "/tmp/rke2-coredns-config.yaml"
    ssh_exec "$node_ip" "
      sudo mv /tmp/rke2-coredns-config.yaml /var/lib/rancher/rke2/server/manifests/rke2-coredns-config.yaml
      sudo chmod 600 /var/lib/rancher/rke2/server/manifests/rke2-coredns-config.yaml
    "
    rm -f /tmp/coredns-patched.yaml
  else
    log "[4/7] Non-init master — skipping manifest deploy"
  fi

  # ── STEP 5: Kernel sysctl ─────────────────────────────────────────────────
  log "[5/7] Applying kernel settings..."
  ssh_exec "$node_ip" "
    sudo sysctl -w kernel.panic=10
    sudo sysctl -w kernel.panic_on_oops=1
    grep -q 'kernel.panic=10' /etc/sysctl.d/99-rke2.conf 2>/dev/null || echo 'kernel.panic=10' | sudo tee -a /etc/sysctl.d/99-rke2.conf
    grep -q 'kernel.panic_on_oops' /etc/sysctl.d/99-rke2.conf 2>/dev/null || echo 'kernel.panic_on_oops=1' | sudo tee -a /etc/sysctl.d/99-rke2.conf
    sudo sysctl --system > /dev/null
  "

  # ── STEP 6: Start service ─────────────────────────────────────────────────
  if service_active "$node_ip"; then
    log "[6/7] rke2-server already active — restarting to pick up config changes"
    ssh_exec "$node_ip" "sudo systemctl restart rke2-server"
  else
    log "[6/7] Starting rke2-server..."
    ssh_exec "$node_ip" "
      sudo systemctl daemon-reload
      sudo systemctl enable rke2-server
      sudo systemctl start rke2-server
    "
  fi

  # ── STEP 7: Wait for Ready ────────────────────────────────────────────────
  log "[7/7] Waiting for node to become Ready (max 10 min)..."
  local max_wait=600
  local waited=0
  until node_is_ready "$node_ip"; do
    sleep 15
    waited=$((waited + 15))
    if [[ $waited -ge $max_wait ]]; then
      log "  Timeout — last journal lines:"
      ssh_exec "$node_ip" "journalctl -u rke2-server --no-pager -n 10" || true
      err "Timeout waiting for RKE2 on ${node_ip}"
    fi
    log "  Still waiting... (${waited}/${max_wait}s)"
  done

  log "✓ Node ${node_ip} Ready"

  # Retrieve kubeconfig from init master
  if [[ "$is_init" == "true" ]]; then
    retrieve_kubeconfig "$node_ip"
  fi
}

retrieve_kubeconfig() {
  local node_ip="$1"
  log "Saving kubeconfig → ${SECRETS_DIR}/kubeconfig-admin.yaml"
  mkdir -p "${SECRETS_DIR}"
  # Use the init master's direct IP, not the VIP — kube-vip can fail to advertise
  # during bootstrap, leaving the VIP unreachable. Direct IP always works.
  ssh_exec "$node_ip" "sudo cat /etc/rancher/rke2/rke2.yaml" | \
    sed "s/127.0.0.1/${node_ip}/g" > "${SECRETS_DIR}/kubeconfig-admin.yaml"
  chmod 600 "${SECRETS_DIR}/kubeconfig-admin.yaml"
}

generate_kubevip_manifest() {
  local vip="$1"
  local iface="$2"
  cat << EOF
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:kube-vip-role
rules:
  - apiGroups: [""]
    resources: ["services","services/status","nodes","endpoints"]
    verbs: ["list","get","watch","update"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["list","get","watch","create","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:kube-vip-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-vip-role
subjects:
  - kind: ServiceAccount
    name: kube-vip
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: kube-vip-ds
  template:
    metadata:
      labels:
        app: kube-vip-ds
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
      containers:
        - name: kube-vip
          image: ghcr.io/kube-vip/kube-vip:v0.7.2
          args: [manager]
          env:
            - name: vip_arp
              value: "true"
            - name: vip_interface
              value: "${iface}"
            - name: address
              value: "${vip}"
            - name: port
              value: "6443"
            - name: vip_cidr
              value: "32"
            - name: cp_enable
              value: "true"
            - name: cp_namespace
              value: kube-system
            # svc_enable / lb_enable are intentionally OFF: kube-vip's IPVS
            # service LB requires IPVS kernel modules and duplicates Cilium's
            # eBPF-based kube-proxy replacement (which already handles
            # LoadBalancer services). We only need the control-plane VIP.
            - name: svc_enable
              value: "false"
            - name: lb_enable
              value: "false"
          securityContext:
            capabilities:
              add: [NET_ADMIN, NET_RAW]
          volumeMounts:
            - mountPath: /etc/kubernetes/admin.conf
              name: kubeconfig
      hostNetwork: true
      # kube-vip v0.7.2 hardcodes the apiserver URL to "https://kubernetes:<port>".
      # With hostNetwork=true, default dnsPolicy=ClusterFirst falls back to host
      # /etc/resolv.conf, which can't resolve "kubernetes". ClusterFirstWithHostNet
      # routes DNS through CoreDNS so the rewrite/hosts override (see
      # rke2-coredns-config.yaml HelmChartConfig) can answer.
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: kube-vip
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      volumes:
        - name: kubeconfig
          hostPath:
            path: /etc/rancher/rke2/rke2.yaml
EOF
}

# ─── Main ─────────────────────────────────────────────────────────────────────

main() {
  log "========================================="
  log "RKE2 Master Install — ${CLUSTER_NAME}"
  log "VIP: ${CONTROL_PLANE_VIP}  Version: ${RKE2_VERSION}"
  log "========================================="

  mkdir -p "${SECRETS_DIR}"

  mapfile -t MASTER_LINES < <(awk '/^\[masters\]/{f=1; next} /^\[/{f=0} f && NF && $0 ~ /ansible_host=/' "$INVENTORY")

  local idx=0
  for line in "${MASTER_LINES[@]}"; do
    [[ -z "$line" ]] && continue

    local node_ip is_init config_file
    node_ip=$(echo "$line"    | grep -oP 'ansible_host=\K[^ ]+')
    is_init=$(echo "$line"    | grep -oP 'is_init_node=\K[^ ]+' || echo "false")
    config_file="${CONFIGS_DIR}/master-$((idx + 1))-config.yaml"

    [[ -f "$config_file" ]] || err "Config not found: ${config_file}"

    if [[ "$is_init" =~ ^[Tt]rue$ ]]; then
      install_master "$node_ip" "true" "$config_file"
    else
      log "Waiting 20s before joining master ${node_ip}..."
      sleep 20
      install_master "$node_ip" "false" "$config_file"
    fi

    idx=$((idx + 1))
  done

  log ""
  log "========================================="
  log "All masters Ready. Run: ./install-worker.sh"
  log "Kubeconfig: ${SECRETS_DIR}/kubeconfig-admin.yaml"
  log "Test: kubectl --kubeconfig ${SECRETS_DIR}/kubeconfig-admin.yaml get nodes"
  log "========================================="
}

main "$@"
