# Ansible/Script inventory generated by Terraform
# Use with rke2/scripts/install-master.sh and install-worker.sh

[all:vars]
ansible_user=${ssh_user}
ansible_ssh_private_key_file=${ssh_private_key}
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
control_plane_vip=${control_plane_vip}
rke2_version=${rke2_version}
rke2_cni=${rke2_cni}
cluster_cidr=${cluster_cidr}
service_cidr=${service_cidr}
cluster_name=${cluster_name}

[masters]
%{ for m in masters ~}
${m.hostname} ansible_host=${m.ip} is_init_node=${m.is_primary}
%{ endfor ~}

[workers]
%{ for w in workers ~}
${w.hostname} ansible_host=${w.ip}
%{ endfor ~}

[masters:vars]
node_role=master

[workers:vars]
node_role=worker
