# RKE2 Server (Control Plane) Configuration
# Generated by Terraform for node: ${node_name}
# Role: ${ is_init_node ? "Bootstrap (init) master" : "Additional master" }

%{ if is_init_node ~}
# This is the BOOTSTRAP master — cluster token is initialized here.
# cluster-init: true causes RKE2 to create a new etcd cluster.
cluster-init: true
%{ else ~}
# Join via master-1 direct IP — VIP only exists after kube-vip starts on master-1
server: https://${init_node_ip}:9345
%{ endif ~}

# Node identity
node-name: ${node_name}
node-ip: ${node_ip}

# HA Virtual IP — all masters and workers connect through this
tls-san:
  - ${control_plane_vip}
  - ${node_ip}
  - ${node_name}
%{ for ip in master_ips ~}
  - ${ip}
%{ endfor ~}

# Networking
cni: ${cni}
cluster-cidr: ${cluster_cidr}
service-cidr: ${service_cidr}
cluster-dns: ${cluster_dns}
cluster-domain: cluster.local

# etcd configuration (performance tuning for production)
etcd-arg:
  - "heartbeat-interval=250"
  - "election-timeout=5000"
  - "quota-backend-bytes=8589934592"    # 8 GB quota
  - "auto-compaction-mode=periodic"
  - "auto-compaction-retention=8h"
  - "max-request-bytes=33554432"         # 32 MB max request

# etcd snapshots — stored locally, external backup also configured
etcd-snapshot-schedule-cron: "0 */6 * * *"   # Every 6 hours
etcd-snapshot-retention: 10
etcd-snapshot-dir: /var/lib/rancher/rke2/server/db/snapshots

# Kube-apiserver hardening
kube-apiserver-arg:
  - "audit-log-path=/var/lib/rancher/rke2/server/logs/audit.log"
  - "audit-log-maxage=30"
  - "audit-log-maxbackup=10"
  - "audit-log-maxsize=100"
  - "audit-policy-file=/etc/rancher/rke2/audit-policy.yaml"
  - "enable-admission-plugins=NodeRestriction,PodSecurity"
  - "request-timeout=60s"
  - "anonymous-auth=false"
  - "authorization-mode=Node,RBAC"
  - "tls-min-version=VersionTLS12"
  - "tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"

# Kube-controller-manager hardening
kube-controller-manager-arg:
  - "terminated-pod-gc-threshold=10"
  - "node-monitor-period=4s"
  - "node-monitor-grace-period=16s"

# Kube-scheduler
kube-scheduler-arg:
  - "bind-address=127.0.0.1"

# Kubelet configuration
kubelet-arg:
  - "max-pods=110"
  - "eviction-hard=memory.available<500Mi,nodefs.available<10%"
  - "eviction-soft=memory.available<1Gi,nodefs.available<15%"
  - "eviction-soft-grace-period=memory.available=1m30s,nodefs.available=1m30s"
  - "system-reserved=cpu=250m,memory=512Mi"
  - "kube-reserved=cpu=250m,memory=512Mi"
  - "rotate-certificates=true"
  - "protect-kernel-defaults=true"
  - "read-only-port=0"
  - "streaming-connection-idle-timeout=4h"
  - "make-iptables-util-chains=true"

# Disable components not needed on masters (run only on workers)
disable:
  - rke2-ingress-nginx    # Disabled — Cilium IngressController is used instead (rke2-cilium-config.yaml)

# Write kubeconfig to a well-known location
write-kubeconfig-mode: "0640"

# Log verbosity (2 = INFO, increase for debugging)
# v: 2
