# RKE2 Agent (Worker) Configuration
# Generated by Terraform for node: ${node_name}

# Connect to cluster through the HA VIP
server: https://${control_plane_vip}:9345

# Node identity
node-name: ${node_name}
node-ip: ${node_ip}

# Kubelet configuration
kubelet-arg:
  - "max-pods=110"
  - "eviction-hard=memory.available<500Mi,nodefs.available<10%"
  - "eviction-soft=memory.available<1Gi,nodefs.available<15%"
  - "eviction-soft-grace-period=memory.available=1m30s,nodefs.available=1m30s"
  - "system-reserved=cpu=200m,memory=512Mi"
  - "kube-reserved=cpu=200m,memory=256Mi"
  - "rotate-certificates=true"
  - "protect-kernel-defaults=true"
  - "read-only-port=0"
  - "make-iptables-util-chains=true"

# Worker-specific labels for scheduling
node-label:
  - "node-role.kubernetes.io/worker=true"
  - "cluster=${cluster_name}"

# Cilium replaces kube-proxy via eBPF; stop the agent from also
# deploying RKE2's static-pod kube-proxy (matches master config).
disable-kube-proxy: true
