################################################################################
# argocd.tfvars — cluster: fxview-test
# Generated by new-cluster.sh on 2026-05-26T14:01:50+00:00.
################################################################################

kubeconfig_path  = "../../clusters/fxview-test/kubeconfig.yaml"
cluster_name     = "fxview-test"
environment      = "Development"

argocd_namespace     = "argocd"
argocd_chart_version = "8.3.0"

argocd_ha_enabled          = false
argocd_server_service_type = "ClusterIP"
argocd_server_insecure     = true

argocd_server_cpu_request    = "100m"
argocd_server_memory_request = "256Mi"
argocd_server_cpu_limit      = "500m"
argocd_server_memory_limit   = "512Mi"

argocd_ingress_enabled       = true
argocd_hostname              = "argocd.fxview-test.internal"
argocd_cluster_issuer        = "cluster-ca-issuer"
argocd_lb_ip_pool_cidr       = "10.10.16.78/32"
argocd_lb_l2_interface_regex = "^(eth|ens|enp).*"
