################################################################################
# proxmox.tfvars — VM provisioning for cluster: fxview-test
# Generated by new-cluster.sh on 2026-05-26T14:01:50+00:00.
################################################################################

cluster_name = "fxview-test"
environment  = "Development"

proxmox_api_url      = "https://10.10.16.249:8006/api2/json"
proxmox_username     = "terraform@pve"
proxmox_tls_insecure = true
proxmox_node         = "pve-4"

shared_cloud_init_snippet_file_id = "local:snippets/k8s-common.yaml"

network_bridge              = "vmbr0"
network_subnet_cidr         = "10.10.16.0/24"
network_gateway             = "10.10.16.1"
dns_servers                 = ["8.8.8.8"]
domain_name                 = "cluster.internal"
vlan_tag                    = 0
control_plane_vip           = "10.10.16.77"
control_plane_vip_interface = "eth0"

vm_template_id      = 9200
vm_template_storage = "local-lvm"

vm_ssh_public_key       = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINWEtprN82zfB18A3+Bg5fgvSpw0jUNsNpktYb1yAUq7 rke2-cluster-deploy"
vm_ssh_private_key_path = "~/.ssh/rke2_cluster_id"
vm_user                 = "ubuntu"
vm_cpu_type             = "x86-64-v2-AES"

master_count             = 3
master_vm_id_start       = 401
master_cpu_cores         = 2
master_cpu_sockets       = 1
master_memory_mb         = 8192
master_disk_size_gb      = 50
master_etcd_disk_size_gb = 20
master_disk_storage      = "pve-4-storage"
master_name_prefix       = "fxview-test-m"
master_ip_addresses      = ["10.10.16.71", "10.10.16.72", "10.10.16.73"]

worker_count             = 3
worker_vm_id_start       = 410
worker_cpu_cores         = 8
worker_cpu_sockets       = 1
worker_memory_mb         = 16384
worker_disk_size_gb      = 100
worker_data_disk_size_gb = 20
worker_disk_storage      = "pve-4-storage"
worker_name_prefix       = "fxview-test-w"
worker_ip_addresses      = ["10.10.16.74", "10.10.16.75", "10.10.16.76"]

rke2_version      = "v1.32.10+rke2r1"
rke2_cni          = "cilium"
rke2_cluster_cidr = "10.42.0.0/16"
rke2_service_cidr = "10.43.0.0/16"
rke2_cluster_dns  = "10.43.0.10"

tags = {
  managed_by  = "terraform"
  cluster     = "fxview-test"
  environment = "Development"
  team        = "devops"
}
